CREATE DATABASE PROYECTO_VOLUNTARIADO2
DROP DATABASE PROYECTO_VOLUNTARIADO2
GO
USE PROYECTO_VOLUNTARIADO2

-- TABLA TIPO DE ACTIVIDAD
CREATE TABLE TIPO_ACTIVIDAD (
    NOMBRE NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_TIPO_ACTIVIDAD PRIMARY KEY (NOMBRE)
);
ALTER TABLE TIPO_ACTIVIDAD 
ADD CONSTRAINT CHK_TIPO_VOLUNTARIADO 
CHECK (NOMBRE IN ('SOCIAL','AMBIENTAL','TÉCNICO','EDUCACIONAL'));

-- TABLA VOLUNTARIO
CREATE TABLE VOLUNTARIO (
    DNI NVARCHAR(9) NOT NULL CHECK (DNI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'),
    NOMBRE NVARCHAR(20) NOT NULL,
    APELLIDO1 NVARCHAR(20) NOT NULL,
    APELLIDO2 NVARCHAR(20),
    EMAIL NVARCHAR(100) NOT NULL,
    FECHANACI DATE NOT NULL,
    DIRECCION NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_VOLUNTARIO PRIMARY KEY (DNI)
);

ALTER TABLE VOLUNTARIO
ADD CONSTRAINT CHK_DNI_FORMAT CHECK (DNI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]');


-- TABLA ORGANIZACIONES
CREATE TABLE ORGANIZACIONES (
    NIF NVARCHAR(9) NOT NULL CHECK (NIF LIKE '[A-Z][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    NOMBRE NVARCHAR(50) NOT NULL,
    ACTIVIDAD_ECONOMICA TEXT,
    TELEFONO VARCHAR(20),
    LOCALIDAD NVARCHAR(50),
    CONSTRAINT PK_ORGANIZACIONES PRIMARY KEY (NIF)
);
ALTER TABLE ORGANIZACIONES
ADD CONSTRAINT CHK_NIF_FORMAT CHECK (NIF LIKE '[A-Z][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]');

-- TABLA ACTIVIDAD
CREATE TABLE ACTIVIDAD (
    CODACTIVIDAD SMALLINT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    ESTADO NVARCHAR(10) NOT NULL CHECK (ESTADO IN ('DISPONIBLE', 'COMPLETO')),
    DESCRIPCION TEXT NOT NULL,
    FECHAINICIO DATE NOT NULL CHECK (FECHAINICIO <= GETDATE()),
    FECHAFIN DATE NOT NULL,
    CAPACIDAD INT NOT NULL,
    NIF_ORG NVARCHAR(9) NOT NULL,
    NOMBRE_TIPOACT NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_ACTIVIDAD PRIMARY KEY (CODACTIVIDAD),
    CONSTRAINT FK_ACTIVIDAD_ORG FOREIGN KEY (NIF_ORG) REFERENCES ORGANIZACIONES (NIF),
    CONSTRAINT FK_ACTIVIDAD_TIPO FOREIGN KEY (NOMBRE_TIPOACT) REFERENCES TIPO_ACTIVIDAD (NOMBRE)
);
ALTER TABLE ACTIVIDAD
ADD CONSTRAINT CHK_NIF_ORG_FORMAT CHECK (NIF_ORG LIKE '[A-Z][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]');

ALTER TABLE ACTIVIDAD
ADD CONSTRAINT CHK_FECHA_INICIO CHECK (FECHAINICIO <= GETDATE() AND FECHAINICIO <= FECHAFIN);

-- TABLA TELÉFONO
CREATE TABLE TELEFONO (
    DNI NVARCHAR(9) NOT NULL,
    NUMTELF VARCHAR(9) NOT NULL,
    CONSTRAINT PK_TELEFONO PRIMARY KEY (DNI, NUMTELF),
    CONSTRAINT FK_TELEFONO_VOLUNTARIO FOREIGN KEY (DNI) REFERENCES VOLUNTARIO (DNI)
);

-- TABLA DISPONIBILIDAD
CREATE TABLE DISPONIBILIDAD (
    DNI NVARCHAR(9) NOT NULL,
    DIASEMANA NVARCHAR(10) NOT NULL CHECK (DIASEMANA IN ('LUNES','MARTES','MIÉRCOLES','JUEVES','VIERNES','SÁBADO','DOMINGO')),
    CONSTRAINT PK_DISPONIBILIDAD PRIMARY KEY (DNI, DIASEMANA),
    CONSTRAINT FK_DISPONIBILIDAD_VOLUNTARIO FOREIGN KEY (DNI) REFERENCES VOLUNTARIO (DNI)
);
ALTER TABLE DISPONIBILIDAD
ADD CONSTRAINT CHK_DIASEMANA CHECK (DIASEMANA IN ('LUNES','MARTES','MIÉRCOLES','JUEVES','VIERNES','SÁBADO','DOMINGO'));

-- TABLA PARTICIPA ENTRE VOLUNTARIO Y ACTIVIDAD
CREATE TABLE PARTICIPA_VOLUNTARIO_ACTIVIDAD (
    DNI NVARCHAR(9) NOT NULL,
    CODACTIVIDAD SMALLINT NOT NULL,
    CONSTRAINT PK_PARTICIPA PRIMARY KEY (DNI, CODACTIVIDAD),
    CONSTRAINT FK_PARTICIPA_VOLUNTARIO FOREIGN KEY (DNI) REFERENCES VOLUNTARIO (DNI),
    CONSTRAINT FK_PARTICIPA_ACTIVIDAD FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDAD (CODACTIVIDAD)
);

-- TABLA PREFIERE ENTRE VOLUNTARIO Y TIPO DE ACTIVIDAD
CREATE TABLE PREFIERE_VOLUNTARIO_TIPOACTIVIDAD (
    DNI NVARCHAR(9) NOT NULL,
    NOMBRE_TIPOACT NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_PREFIERE PRIMARY KEY (DNI, NOMBRE_TIPOACT),
    CONSTRAINT FK_PREFIERE_VOLUNTARIO FOREIGN KEY (DNI) REFERENCES VOLUNTARIO (DNI),
    CONSTRAINT FK_PREFIERE_TIPOACT FOREIGN KEY (NOMBRE_TIPOACT) REFERENCES TIPO_ACTIVIDAD (NOMBRE)
);

-- TABLA ODS
CREATE TABLE ODS (
    NUMODS SMALLINT NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    DESCRIPCION TEXT,
    CONSTRAINT PK_ODS PRIMARY KEY (NUMODS)
);

-- TABLA CONTIENE ENTRE ACTIVIDAD Y ODS
CREATE TABLE CONTIENE_VOLUNTARIADO_ODS (
    CODACTIVIDAD SMALLINT NOT NULL,
    NUMODS SMALLINT NOT NULL,
    CONSTRAINT PK_CONTIENE PRIMARY KEY (CODACTIVIDAD, NUMODS),
    CONSTRAINT FK_CONTIENE_ACTIVIDAD FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDAD (CODACTIVIDAD),
    CONSTRAINT FK_CONTIENE_ODS FOREIGN KEY (NUMODS) REFERENCES ODS (NUMODS)
);

-- TABLA NOTICIAS
CREATE TABLE NOTICIAS (
    CODNOTICIA SMALLINT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    TIPO VARCHAR(20) CHECK (TIPO IN ('Noticia', 'Evento', 'Actividad Nueva', 'Otro Tipo')),
    FECHAPUBLI DATE NOT NULL,
    CODACTIVIDAD SMALLINT,
    CONSTRAINT PK_NOTICIAS PRIMARY KEY (CODNOTICIA),
    CONSTRAINT FK_NOTICIAS_ACTIVIDAD FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDAD (CODACTIVIDAD)
);

ALTER TABLE NOTICIAS
ADD CONSTRAINT CHK_TIPO_NOTICIA CHECK (TIPO IN ('Noticia', 'Evento', 'Actividad Nueva', 'Otro Tipo'));




GO
CREATE RULE TIPO_VOLUNTARIADO AS (@CAMPO IN ('SOCIAL','AMBIENTAL','TÉCNICO','EDUCACIONAL'))
GO
CREATE RULE NIFS AS (@CAMPO LIKE '[A-Z][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
GO
CREATE RULE DNI AS (@CAMPO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')
GO
CREATE RULE DIA_SEMANA AS (@CAMPO IN ('LUNES','MARTES','MIÉRCOLES','JUEVES','VIERNES','SÁBADO','DOMINGO')) 
GO
CREATE RULE REGLA_TIPO_NOTICIA AS (@CAMPO IN('Noticia','Evento','Actividad Nueva','Otro Tipo'))
GO
--BINDRULE NIFS
EXEC SP_BINDRULE NIFS, 'ORGANIZACIONES.NIF'
EXEC SP_BINDRULE NIFS, 'ACTIVIDAD.NIF_ORG'
--BINDRULE DNI
EXEC SP_BINDRULE DNI, 'VOLUNTARIO.DNI'
EXEC SP_BINDRULE DNI, 'TELEFONO.DNI'
EXEC SP_BINDRULE DNI, 'DISPONIBILIDAD.DNI'
EXEC SP_BINDRULE DNI, 'PARTICIPA_VOLUNTARIO_ACTIVIDAD.DNI'
--BINDRULE DIA_SEMANA
EXEC SP_BINDRULE DIA_SEMANA, 'DISPONIBILIDAD.DIASEMANA'
