CREATE DATABASE PROYECTO_VOLUNTARIADO
GO
USE PROYECTO_VOLUNTARIADO
--TABLA TIPO DE ACTIVIDAD
CREATE TABLE TIPO_ACTIVIDAD(
	NOMBRE NVARCHAR(20) NOT NULL, --HACER RULE
	CONSTRAINT PK_TIPO_ACTIVIDAD PRIMARY KEY (NOMBRE), --CLAVE PRIMARIA
)
--TABLA VOLUNTARIO
CREATE TABLE VOLUNTARIO(
	DNI NVARCHAR(9) NOT NULL,
	NOMBRE NVARCHAR(20) NOT NULL,
	APELLIDO1 NVARCHAR(20) NOT NULL,
	APELLIDO2 NVARCHAR(20) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
	FECHANACI DATETIME NOT NULL,
	DIRECCION NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_VOLUNTARIO PRIMARY KEY (DNI) --CLAVE PRIMARIA
)
--TABLA ORGANIZACIONES
CREATE TABLE ORGANIZACIONES (
    NIF NVARCHAR(9) NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
    ACTIVIDAD_ECONOMICA TEXT,
    TELÉFONO VARCHAR(20),
    LOCALIDAD NVARCHAR(50),
	CONSTRAINT PK_ORGANIZACIONES PRIMARY KEY (NIF), --CLAVE PRIMARIA
)
--TABLA ACTIVIDAD
CREATE TABLE ACTIVIDAD(
	CODACTIVIDAD SMALLINT IDENTITY(1,1) NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	ESTADO BIT CHECK(ESTADO IN ('DISPONIBLE','COMPLETO')) NOT NULL,
	DESCRIPCION TEXT NOT NULL,
	FECHAINICIO DATETIME NOT NULL,
	FECHAFIN DATETIME NOT NULL,
	CAPACIDAD INT NOT NULL,
    NIF_ORG NVARCHAR(9) NOT NULL,
	NOMBRE_TIPOACT NVARCHAR(20) NOT NULL, --TIENE RULE
	CONSTRAINT PK_ACTIVIDAD PRIMARY KEY (CODACTIVIDAD), --CLAVE PRIMARIA
	CONSTRAINT FK_ACTIVIDAD_ORG FOREIGN KEY(NIF_ORG) REFERENCES ORGANIZACIONES(NIF),--CLAVE EXTERNA
	CONSTRAINT FK_PREFIERE_TIPOACTIVIDAD FOREIGN KEY(NOMBRE_TIPOACT) REFERENCES TIPO_ACTIVIDAD(NOMBRE)--CLAVE EXTERNA

)
--TABLA TELÉFONO
CREATE TABLE TELEFONO(
	DNI NVARCHAR(9) NOT NULL,
	NUMTELF VARCHAR(9) NOT NULL,
	CONSTRAINT PK_VOLUNTARIO PRIMARY KEY (DNI, NUMTELF), --CLAVE PRIMARIA
	CONSTRAINT FK_TELEFONO_VOLUNTARIO FOREIGN KEY(DNI) REFERENCES VOLUNTARIO(DNI)--CLAVE EXTERNA
)

--TABLA DISPONIBILIDAD
CREATE TABLE DISPONIBILIDAD (
	DNI NVARCHAR(9) NOT NULL,
	DIASEMANA NVARCHAR(20) NOT NULL, --HACER RULE
	CONSTRAINT PK_VOLUNTARIO PRIMARY KEY (DNI, DIASEMANA), --CLAVE PRIMARIA
	CONSTRAINT FK_DISPONIBILIDAD_VOLUNTARIO FOREIGN KEY(DNI) REFERENCES VOLUNTARIO(DNI)--CLAVE EXTERNA

)

--TABLA PARTICIPA ENTRE VOLUNTARIO Y ACTIVIDAD
CREATE TABLE PARTICIPA_VOLUNTARIO_ACTIVIDAD(
	DNI NVARCHAR(9) NOT NULL, --TIENE RULE
	CODACTIVIDAD SMALLINT IDENTITY(1,1),
	CONSTRAINT PK_VOLUNTARIO PRIMARY KEY (DNI, CODACTIVIDAD), --CLAVE PRIMARIA
	CONSTRAINT FK_PARTICIPA_VOLUNTARIO FOREIGN KEY(DNI) REFERENCES VOLUNTARIO(DNI),--CLAVE EXTERNA
	CONSTRAINT FK_PARTICIPA_ACTIVIDADES FOREIGN KEY(CODACTIVIDAD) REFERENCES ACTIVIDAD(CODACTIVIDAD)--CLAVE EXTERNA

)

--TABLA PREFIERE ENTRE VOLUNTARIO Y TIPO DE ACTIVIDAD
CREATE TABLE PREFIERE_VOLUNTARIO_TIPOACTIVIDAD(
	DNI NVARCHAR(9) NOT NULL, --TIENE RULE
	NOMBRE_TIPOACT NVARCHAR(20) NOT NULL, --TIENE RULE
	CONSTRAINT PK_PREFIERE_VOLUNTARIO_TIPOACTIVIDAD PRIMARY KEY (DNI, NOMBRE_TIPOACT), --CLAVE PRIMARIA
	CONSTRAINT FK_PREFIERE_VOLUNTARIO FOREIGN KEY(DNI) REFERENCES VOLUNTARIO(DNI),--CLAVE EXTERNA
	CONSTRAINT FK_PREFIERE_TIPOACTIVIDAD FOREIGN KEY(NOMBRE_TIPOACT) REFERENCES TIPO_ACTIVIDAD(NOMBRE)--CLAVE EXTERNA
)

--TABLA PERTENECE ENTRE ACTIVIDAD Y TIPO ACTIVIDAD
CREATE TABLE PERTENECE_ACTIVIDAD_TIPOACTIVIDAD(
	CODACTIVIDAD SMALLINT IDENTITY(1,1),
	NOMBRE_TIPOACT NVARCHAR(20) NOT NULL, --TIENE RULE
	CONSTRAINT PK_PERTENECE_ACTIVIDAD_TIPOACTIVIDAD PRIMARY KEY (CODACTIVIDAD, NOMBRE_TIPOACT), --CLAVE PRIMARIA
	CONSTRAINT FK_PERTENECE_ACTIVIDAD FOREIGN KEY(CODACTIVIDAD) REFERENCES ACTIVIDAD(CODACTIVIDAD),--CLAVE EXTERNA
	CONSTRAINT FK_PERTENECE_TIPOACTIVIDAD FOREIGN KEY(NOMBRE_TIPOACT) REFERENCES TIPO_ACTIVIDAD(NOMBRE),--CLAVE EXTERNA
)



--TABLA ODS
CREATE TABLE ODS(
	NUMODS SMALLINT NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	DESCRIPCION TEXT
	CONSTRAINT PK_ODS PRIMARY KEY (NUMODS), --CLAVE PRIMARIA
)

--TABLA CONTIENE ENTRE VOLUNTARIADO Y ODS
CREATE TABLE CONTIENE_VOLUNTARIADO_ODS(
	CODACTIVIDAD SMALLINT IDENTITY(1,1),
	NUMODS SMALLINT NOT NULL
	CONSTRAINT PK_ODS PRIMARY KEY (CODACTIVIDAD, NUMODS), --CLAVE PRIMARIA
	CONSTRAINT FK_CONTIENE_ACTIVIDAD FOREIGN KEY(CODACTIVIDAD) REFERENCES ACTIVIDAD(CODACTIVIDAD),--CLAVE EXTERNA
	CONSTRAINT FK_CONTIENE_ODS FOREIGN KEY(NUMODS) REFERENCES ODS(NUMODS),--CLAVE EXTERNA
)

--TABLA NOTICIAS
CREATE TABLE NOTICIAS(
	CODNOTICIA SMALLINT IDENTITY(1,1),
	NOMBRE NVARCHAR(50) NOT NULL,
	TIPO VARCHAR(20),
	FECHAPUBLI DATETIME NOT NULL,
	CODACTIVIDAD SMALLINT IDENTITY(1,1)
	CONSTRAINT PK_NOTICIAS PRIMARY KEY (CODNOTICIA), --CLAVE PRIMARIA
	CONSTRAINT FK_NOTICIAS_ACTIVIDAD FOREIGN KEY(CODACTIVIDAD) REFERENCES ACTIVIDAD(CODACTIVIDAD),--CLAVE EXTERNA
)



GO
CREATE RULE TIPO_VOLUNTARIADO AS (@CAMPO IN ('SOCIAL','AMBIENTAL','TÉCNICO','EDUCACIONAL'))
GO
CREATE RULE NIFS AS (@CAMPO LIKE '[A-Z][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
GO
CREATE RULE DNI AS (@CAMPO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')
GO
CREATE RULE DIA_SEMANA AS (@CAMPO IN ('LUNES','MARTES','MIÉRCOLES','JUEVES','VIERNES','SÁBADO','DOMINGO')) 
GO
CREATE RULE REGLA_TIPO_NOTICIA AS (@CAMPO IN('Noticia','Evento','Actividad Nueva','Otro Tipo'))
GO
CREATE RULE FECHA_INICIO_ACTIVIDAD AS (@CAMPO<=GETDATE() OR @CAMPO <=ACTIVIDAD.FECHAFIN)
GO

--BINDRULE TIPO_VOLUNTARIADO
EXEC SP_BINDRULE TIPO_VOLUNTARIADO, 'TIPO_VOLUNTARIADO.NOMBRE'
EXEC SP_BINDRULE TIPO_VOLUNTARIADO, 'PREFIERE_VOLUNTARIO_TIPOVOLUNTARIADO.NOMBRE_TIPOACT'
EXEC SP_BINDRULE TIPO_VOLUNTARIADO, 'PERTENECE_ACTIVIDAD_TIPOVOLUNTARIADO.NOMBRE'
--BINDRULE NIFS
EXEC SP_BINDRULE NIFS, 'ORGANIZACIONES.NIF'
EXEC SP_BINDRULE NIFS, 'ACTIVIDAD.NIF_ORG'
--BINDRULE DNI
EXEC SP_BINDRULE DNI, 'VOLUNTARIO.DNI'
EXEC SP_BINDRULE DNI, 'TELEFONO.DNI'
EXEC SP_BINDRULE DNI, 'DISPONIBILIDAD.DNI'
EXEC SP_BINDRULE DNI, 'PARTICIPA_VOLUNTARIO_ACTIVIDAD.DNI'
--BINDRULE DIA_SEMANA
EXEC SP_BINDRULE DIA_SEMANA, 'DISPONIBILIDAD.DIASEMANA'
--BINDRULE FECHA INICIO ACTIVIDAD
EXEC SP_BINDRULE FECHA_INICIO_ACTIVIDAD, 'ACTIVIDAD.FECHAINICIO'